Small word fixes
ONSgeo/geospatial-training pull request #4
Opened 2024-02-11 15:23 UTC by rhoded2

2024-02-13 11:08 UTC, donnaviney commented on _docs/awareness_of_geog_and_stats.md
Awareness of Geography and Stats:

Line 106 - postcode should be singular.

Line 108 - do we need to spell out the acronym.

2024-02-13 13:56 UTC, donnaviney commented on _docs/intro_to_qgis.md
Intro to QGIS:

Line 126 - typo on "delimited".  Also a double full stop at the end of that paragraph.
Line 191 - need a "d" on the end of the word "place".
Line 217 - Need "ly" on the end of the word "common"
Line 283 - typo on Edinburgh

2024-02-13 14:54 UTC, donnaviney commented on _docs/make_a_good_map.md
Line 9 - missing "is" before currently.
Line 66 - Do we need to spell out the acronym?
Line 76 (amended) - should the comma go before the "and so"?
Line 101 - There should be a "d" on the end of "use".
Line 113 - should that be palettes?
Line 205 - should that be "relationship" rather than "relation"?
Line 221 - "website" instead of "web"
Line 231 - The first part of the first sentence does not make sense.
Line 256 - "or" not "of"
Line 279 - replace "time" with "layer"
Line 461 - Add "ly" on the end of "close".
Line 463 (corrected) - should be a lowercase "a" on the second aesthetically.

2024-02-13 14:56 UTC, donnaviney commented on _docs/mapping/Houses_below_60_percent_median_income_Choropleth_Mixing_Boundaries.PNG
Overlapping ranges.

Do we need to spell out the MSOA acronym?

2024-02-13 15:35 UTC, donnaviney commented on _docs/practical_geog_and_stats.md
Practical geog and stats:

Line 37 - "with" not "will"
Line 151 - Add "ed" on the end of "project"
Line 156 - missing word "with"
Line 265 - we should refer to the portal by it's correct name "Open Geography portal" and this will also make it consistent with the rest of the references in the course.
Line 339 - typo on "linkage"
Line 407 - software should be singular
Line 498 - change "raw counts by area as large areas " to "raw counts as large areas "
Line 505 corrected - typo on "area" at the end of the first sentence.
Line 510 - change "keep an out" to "keep an eye out"
Line 524 - Add "d" on the end of "cause".
Line 533 - change "*Precision** is the exact " to "*Precision** is how exact "

2024-02-13 15:37 UTC, donnaviney requested changes
Hi Debbie.  I have reviewed the updated content and you have done a good job of correcting most of it.  I have spotted some additional things that need correcting though.  I have put these in comments against each course.  Thanks.  Donna.

2024-02-26 15:59 UTC, rhoded2 commented on _docs/awareness_of_geog_and_stats.md
Changes made

2024-02-26 16:00 UTC, rhoded2 commented on _docs/make_a_good_map.md
Changes made

2024-02-26 16:01 UTC, rhoded2 commented on _docs/mapping/Houses_below_60_percent_median_income_Choropleth_Mixing_Boundaries.PNG
I have now  included the full name in the text, so we can use the acronym in the title of the map

2024-02-26 16:17 UTC, rhoded2 commented on _docs/practical_geog_and_stats.md
All updated

2024-02-27 11:02 UTC, merged